/* Chapter - 1: Build a Next.js App */

/* Lesson 26: Section 1 Recap */


/* Lesson 25: Model Detail Page */


/* Lesson 24: Dynamic Routes */


/* Lesson 23: Challenge - Create the Models List Page */


/* Lesson 22: Aside: Client vs. Server Components */


/* Lesson 21: Aside: TypeScript Organization in PrintForge */


/* Lesson 20: Challenge - Add Links to Navbar */


/* Lesson 19: Links in Next.js */


/* Lesson 18: Optimizing Images */


/* Lesson 17: Optimizing Fonts */


/* Lesson 16: Challenge - Add Header to PrintForge */


/* Lesson 15: Layouts part 2 */


/* Lesson 14: Layouts part 1 */


/* Lesson 13: Nested Routes */


/* Lesson 12: Challenge - PrintForge About Page */


/* Lesson 11: Challenge - PrintForge Home Page */


/* Lesson 10: PrintForge Challenge Setup */
import './globals.css'
export default function RootLayout({children}:Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body>
        {children}
      </body>
    </html>
  )
}

/* Lesson 9: create-next-app files walkthrough */

/* 
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
 */