import lessonGenerator from "../../Aside/index.js"

const chapterName = "React State"
const chapterNum = 3
const lesson = [
  "Section 3 Intro",
  "Chef Claude: Header",
  "Chef Claude: form",
  "Chef Claude: Project overview",
  "Event Listeners",
  "Chef Claude: Map ingredients list",
  "Props vs. State: Props",
  "Props vs. State: State",
  "useState",
  "useState array destructuring",
  "Changing state",
  "State practice",
  "Updating state with a callback function",
  "Changing state quiz",
  "Ternary practice",
  "Toggling state",
  "Complex state: Arrays",
  "Chef Claude: Refactor array state",
  "Complex state: Objects",
  "Complex state: updating state objects",
  "React forms intro",
  "Form basics",
  "Form submission",
  "Form action",
  "Chef Claude: Refactor form submission",
  "Forms: textarea & defaultValue",
  "Forms: radio",
  "Forms: checkbox",
  "Forms: select and option",
  "Forms: Object.fromEntries",
  "Chef Claude: conditional rendering intro",
  "Conditional rendering: &&",
  "Conditional rendering: Why does && work?",
  "Conditional rendering practice: &&",
  "Conditional rendering: ternary",
  "Conditional rendering practice",
  "Conditional rendering quiz",
  "Chef Claude: conditional rendering challenge 1",
  "Chef Claude: conditional rendering challenge 2",
  "Chef Claude: Get recipe placeholder challenge",
  "Passing state as props",
  "Setting state from child components",
  "Passing data around React",
  "Sound pads challenge, part 1",
  "Dynamic styles",
  "Sound pads challenge, part 2",
  "Sound pads challenge, part 3",
  "Sound pads challenge part 4.1 - local state",
  "Sound pads challenge part 4.2 - shared state",
  "Sound pads challenge part 4.3 - updating item in array",
  "Chef Claude challenge: refactor to separate components",
  "API Sign Ups",
  "AI code walkthrough",
  "Quick AI Update",
  "Challenge quiz: prep to get recipe from the AI chef 🤖👨‍🍳",
  "Challenge: Get recipe from the AI chef 🤖👨‍🍳",
  "Format recipe response",
  "Section 3 Outro"
];

lessonGenerator(chapterName, lesson, chapterNum) 
